
CREATE TABLE DEPARTMENTOS(
    ID_DEP INTEGER PRIMARY KEY,
    NOMBRE VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE LOCALIDADES(
  ID_LOC INTEGER,
  NOMBRE VARCHAR(50) NOT NULL UNIQUE,
  ID_DEPA INTEGER NOT NULL,
  CONSTRAINT FK_DEPA_LOC FOREIGN KEY (ID_DEPA)REFERENCES DEPARTMENTOS (ID_DEP),
  PRIMARY KEY(ID_LOC,ID_DEPA)
);

create table ITRS(
    ID_ITR       INTEGER  primary key,
    NOMBRE       VARCHAR2(30)NOT NULL ,
    ID_DEPAMENTO  INTEGER NOT NULL,
    CONSTRAINT FK_DEP_ITR FOREIGN KEY (ID_DEPAMENTO) REFERENCES DEPARTMENTOS (ID_DEP)
);

CREATE TABLE USERS(
    DOCUMNETO INTEGER PRIMARY KEY,
    TELEFONO VARCHAR(20) NOT NULL,
    MAIL_P VARCHAR(50) NOT NULL UNIQUE,
    MAIL_I VARCHAR(50) NOT NULL UNIQUE,
    ID_DEPA INTEGER NOT NULL,
    GENERO VARCHAR(30) NOT NULL,
    FEC_NAC DATE NOT NULL,
    NOMUSER VARCHAR(20) NOT NULL,
    NOMBRES VARCHAR(50) NOT NULL,
    APELLIDOS VARCHAR(50) NOT NULL,
    PASSUSER VARCHAR(50) NOT NULL,
    ACTIVO NUMBER(0,1),
    CONSTRAINT FK_DEP_USER FOREIGN KEY (ID_DEPA) REFERENCES DEPARTMENTOS (ID_DEP)
);

CREATE TABLE ANALISTAS(
    DOCUMENTO INTEGER PRIMARY KEY,
    FEC_SIS DATE NOT NULL,
    CONSTRAINT FK_ANA_USER FOREIGN KEY (DOCUMENTO) REFERENCES USERS (DOCUMNETO)
);

CREATE TABLE TUTOR(
  DOCUMENTO  INTEGER PRIMARY KEY,
  TIPO VARCHAR(30) NOT NULL ,
  AREA VARCHAR(30) NOT NULL,
  CONSTRAINT FK_TUT_USER FOREIGN KEY (DOCUMENTO) REFERENCES USERS (DOCUMNETO)
);

CREATE TABLE ESTUDIANTE(
    DOCUMENTO INTEGER PRIMARY KEY,
    FEC_INGRESO DATE NOT NULL ,
    CONSTRAINT FK_EST_USER FOREIGN KEY (DOCUMENTO) REFERENCES USERS (DOCUMNETO)
);

CREATE TABLA EVENTOS(
    ID_EVENTO INTERGER primary key,
    TITULO VARCAR(30) NOT NULL,
    FEC_INICIO DATE NOT NULL,
    FEC_FINALIZADO DATE NOT NULL,
    TIPO EVENTO VARCHAR(30) NOT NULL,
    MODALIDAD VARCHAR(30) NOT NULL,
    ID_ITR NUMBER NOT NULL,
    LOCALIZACION VARCHAR(50),
    DOCUMENTO NUMBER NOT NULL,
    CONSTRAINT FK_EVE_ANA FOREIGN KEY (DOCUMENTO) REFERENCES ANALISTA(DOCUMNETO)
);

CREATE TABLA TUTORES(
    IDOCUMENTO NUMBER,
    ID_EVENTO NUMBER,
    CONSTRAINT FK_TUTOR_DOCENTE FOREIGN KEY (DOCUMENTO) REFERENCES DOCENTE (DOCUMNETO),
    CONSTRAINT FK_TUT_EVENTO FOREIGN KEY (ID_EVENTO) REFERENCES EVENTOS(ID_EVENTO),
);